In [125]:
from mxnet import np, npx
#npx.set_np()
x = np.arange(12)
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [126]:
x.shape

(12,)

In [127]:
x.size

12

In [128]:
x.reshape(3, 4)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [129]:
x.reshape(-1, 4)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [130]:
np.empty((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [131]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [132]:
np.ones((3, 4, 5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [133]:
np.random.normal(0, 2, size=(3, 4))

array([[ 3.0388887 , -2.9499323 ,  3.8081756 , -1.0482839 ],
       [-3.1468863 ,  2.5325112 , -0.2801573 ,  1.7901284 ],
       [ 0.59340155, -1.203189  ,  2.6223903 ,  2.4081118 ]])

In [134]:
np.array([[1, 2, 3], [3, 4, 6], [10, 22, 40]])

array([[ 1.,  2.,  3.],
       [ 3.,  4.,  6.],
       [10., 22., 40.]])

In [135]:
x = np.array([1, 2, 3, 5])
y = np.array([2, 0, 5, 5])

x + y, x - y, x * y, x / y, x**y 

(array([ 3.,  2.,  8., 10.]),
 array([-1.,  2., -2.,  0.]),
 array([ 2.,  0., 15., 25.]),
 array([0.5, inf, 0.6, 1. ]),
 array([1.000e+00, 1.000e+00, 2.430e+02, 3.125e+03]))

In [136]:
np.exp(x)

array([  2.7182817,   7.389056 ,  20.085537 , 148.41316  ])

In [137]:
x = np.arange(12).reshape(3, 4)
y = np.array([[1, 2, 3, 5], [3, 4, 5, 7], [4, 5, 6, 0]])

np.concatenate([x, y], axis=0), np.concatenate([x, y], axis=1)



(array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 1.,  2.,  3.,  5.],
        [ 3.,  4.,  5.,  7.],
        [ 4.,  5.,  6.,  0.]]),
 array([[ 0.,  1.,  2.,  3.,  1.,  2.,  3.,  5.],
        [ 4.,  5.,  6.,  7.,  3.,  4.,  5.,  7.],
        [ 8.,  9., 10., 11.,  4.,  5.,  6.,  0.]]))

In [138]:
x == y

array([[False, False, False, False],
       [False, False, False,  True],
       [False, False, False, False]])

In [139]:
x != y

array([[ True,  True,  True,  True],
       [ True,  True,  True, False],
       [ True,  True,  True,  True]])

In [140]:
x.sum()

array(66.)

In [141]:
y.sum()

array(45.)

In [142]:
x = np.arange(3).reshape(3, 1)
y = np.arange(3).reshape(1, 3)
x, y

(array([[0.],
        [1.],
        [2.]]),
 array([[0., 1., 2.]]))

In [143]:
x + y

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [144]:
x == y

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [145]:
x[-1], x[1:2]

(array([2.]), array([[1.]]))

In [156]:
x = np.arange(12).reshape(3, 4)
y = np.arange(12).reshape(3, 4)
x, y

(array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]))

In [147]:
x[2, 2] = 9
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9.,  9., 11.]])

In [148]:
x[0:2, :] =1
x


array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 8.,  9.,  9., 11.]])

In [158]:
before = id(y)
y = y + x
id(y) == before

False